/**:
  ros__parameters:
    image_transport: raw
    family: 25h9
    size: 0.07
    max_hamming: 0
    qos_profile: sensor_data
    detector:
      threads: 2
      decimate: 2.0
      blur: 0.0
      refine: true
      sharpening: 0.25
      debug: false
    pose_estimation_method: pnp
    tag:
      ids: [24]
      frames: [panda_d455_tag24]
      sizes: [0.07]
